name: m3t_api
description: "API client for the m3t Organizer Backend."
version: 1.0.0
publish_to: "none"

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  equatable: ^2.0.8
  http: ^1.2.2
  json_annotation: ^4.11.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  build_runner: ^2.11.1
  json_serializable: ^6.9.0
  test: ^1.30.0
  very_good_analysis: ^10.1.0